# Generated by Django 3.1.4 on 2020-12-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20201228_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email',
        ),
    ]
