# Generated by Django 3.1.4 on 2020-12-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20201229_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
    ]
