# Generated by Django 3.1 on 2021-01-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AlterModelTable(
            name='administrator',
            table='Administrator',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='Orders',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
