# Generated by Django 3.1 on 2021-01-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20210105_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
    ]
