# Generated by Django 3.1 on 2021-01-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
